CREATE DATABASE mundo;
USE mundo; 

CREATE TABLE Pais(
	Id_pais INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(35) NOT NULL, 
    Continente VARCHAR(35) NOT NULL,
    Pop REAL NOT NULL, 
    PIB REAL NOT NULL,
    Expec_vida REAL NOT NULL
);

CREATE TABLE Cidade(
	Id_cidade INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(35) NOT NULL,
    Pais VARCHAR(35) NOT NULL,
    Pop REAL NOT NULL,
    Capital VARCHAR(1) NOT NULL
    
);

CREATE TABLE Rio(
	Id_rio INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(35) NOT NULL,
    Nascente VARCHAR(35) NOT NULL, 
    Pais VARCHAR(35) NOT NULL,
    Comprimento INTEGER NOT NULL
);